# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Processing',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('air_file', models.FileField(upload_to=b'input')),
                ('air_json_data', models.TextField()),
                ('iea_file', models.FileField(upload_to=b'output')),
                ('iea_json_data', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('air_BKAGT', models.TextField(db_index=True, verbose_name=b'BKAGT', blank=True)),
                ('air_CURRCDE', models.TextField(db_index=True, verbose_name=b'CURRCDE', blank=True)),
                ('air_GUOPT', models.TextField(db_index=True, verbose_name=b'GUOPT', blank=True)),
                ('air_HTLNME', models.TextField(db_index=True, verbose_name=b'HTLNME', blank=True)),
                ('air_IDBKG', models.TextField(db_index=True, verbose_name=b'IDBKG', blank=True)),
                ('air_INDTE', models.TextField(db_index=True, verbose_name=b'INDTE', blank=True)),
                ('air_OUTDTE', models.TextField(db_index=True, verbose_name=b'OUTDTE', blank=True)),
                ('air_PNRDTE', models.TextField(db_index=True, verbose_name=b'PNRDTE', blank=True)),
                ('air_PNRRMK_AutCli', models.TextField(db_index=True, verbose_name=b'PNRRMK_AutCli', blank=True)),
                ('air_PNRRMK_CcuPax', models.TextField(db_index=True, verbose_name=b'PNRRMK_CcuPax', blank=True)),
                ('air_PNRRMK_CodCli', models.TextField(db_index=True, verbose_name=b'PNRRMK_CodCli', blank=True)),
                ('air_PNRRMK_CodEt1', models.TextField(db_index=True, verbose_name=b'PNRRMK_CodEt1', blank=True)),
                ('air_PNRRMK_CodEt2', models.TextField(db_index=True, verbose_name=b'PNRRMK_CodEt2', blank=True)),
                ('air_PNRRMK_CodEt3', models.TextField(db_index=True, verbose_name=b'PNRRMK_CodEt3', blank=True)),
                ('air_PNRRMK_CodSgl', models.TextField(db_index=True, verbose_name=b'PNRRMK_CodSgl', blank=True)),
                ('air_PNRRMK_DadCnf', models.TextField(db_index=True, verbose_name=b'PNRRMK_DadCnf', blank=True)),
                ('air_PNRRMK_FilCli', models.TextField(db_index=True, verbose_name=b'PNRRMK_FilCli', blank=True)),
                ('air_PNRRMK_ForRep', models.TextField(db_index=True, verbose_name=b'PNRRMK_ForRep', blank=True)),
                ('air_PNRRMK_MatFun', models.TextField(db_index=True, verbose_name=b'PNRRMK_MatFun', blank=True)),
                ('air_PNRRMK_NomSol', models.TextField(db_index=True, verbose_name=b'PNRRMK_NomSol', blank=True)),
                ('air_PNRRMK_RsvDir', models.TextField(db_index=True, verbose_name=b'PNRRMK_RsvDir', blank=True)),
                ('air_PNRRMK_VlrTch', models.TextField(db_index=True, verbose_name=b'PNRRMK_VlrTch', blank=True)),
                ('air_PSGRNME', models.TextField(db_index=True, verbose_name=b'PSGRNME', blank=True)),
                ('air_ROOMRTE', models.TextField(db_index=True, verbose_name=b'ROOMRTE', blank=True)),
                ('air_SIPPRM', models.TextField(db_index=True, verbose_name=b'SIPPRM', blank=True)),
                ('iea_AgtRsv', models.TextField(db_index=True, verbose_name=b'AgtRsv', blank=True)),
                ('iea_AutCli', models.TextField(db_index=True, verbose_name=b'AutCli', blank=True)),
                ('iea_CcuPax', models.TextField(db_index=True, verbose_name=b'CcuPax', blank=True)),
                ('iea_CcuVen', models.TextField(db_index=True, verbose_name=b'CcuVen', blank=True)),
                ('iea_CodAph', models.TextField(db_index=True, verbose_name=b'CodAph', blank=True)),
                ('iea_CodCli', models.TextField(db_index=True, verbose_name=b'CodCli', blank=True)),
                ('iea_CodEt1', models.TextField(db_index=True, verbose_name=b'CodEt1', blank=True)),
                ('iea_CodEt2', models.TextField(db_index=True, verbose_name=b'CodEt2', blank=True)),
                ('iea_CodEt3', models.TextField(db_index=True, verbose_name=b'CodEt3', blank=True)),
                ('iea_CodFop', models.TextField(db_index=True, verbose_name=b'CodFop', blank=True)),
                ('iea_CodMoe', models.TextField(db_index=True, verbose_name=b'CodMoe', blank=True)),
                ('iea_CodPah', models.TextField(db_index=True, verbose_name=b'CodPah', blank=True)),
                ('iea_CodSgl', models.TextField(db_index=True, verbose_name=b'CodSgl', blank=True)),
                ('iea_CodTar', models.TextField(db_index=True, verbose_name=b'CodTar', blank=True)),
                ('iea_DadCnf', models.TextField(db_index=True, verbose_name=b'DadCnf', blank=True)),
                ('iea_DadPcv', models.TextField(db_index=True, verbose_name=b'DadPcv', blank=True)),
                ('iea_DatCnf', models.TextField(db_index=True, verbose_name=b'DatCnf', blank=True)),
                ('iea_DatFim', models.TextField(db_index=True, verbose_name=b'DatFim', blank=True)),
                ('iea_DatIni', models.TextField(db_index=True, verbose_name=b'DatIni', blank=True)),
                ('iea_DatSol', models.TextField(db_index=True, verbose_name=b'DatSol', blank=True)),
                ('iea_DesCcu', models.TextField(db_index=True, verbose_name=b'DesCcu', blank=True)),
                ('iea_EmlFun', models.TextField(db_index=True, verbose_name=b'EmlFun', blank=True)),
                ('iea_FilCli', models.TextField(db_index=True, verbose_name=b'FilCli', blank=True)),
                ('iea_ForPdt', models.TextField(db_index=True, verbose_name=b'ForPdt', blank=True)),
                ('iea_ForRep', models.TextField(db_index=True, verbose_name=b'ForRep', blank=True)),
                ('iea_GerDoc', models.TextField(db_index=True, verbose_name=b'GerDoc', blank=True)),
                ('iea_GerRet', models.TextField(db_index=True, verbose_name=b'GerRet', blank=True)),
                ('iea_HorFim', models.TextField(db_index=True, verbose_name=b'HorFim', blank=True)),
                ('iea_HorIni', models.TextField(db_index=True, verbose_name=b'HorIni', blank=True)),
                ('iea_IdtArq', models.TextField(db_index=True, verbose_name=b'IdtArq', blank=True)),
                ('iea_IdtDiv', models.TextField(db_index=True, verbose_name=b'IdtDiv', blank=True)),
                ('iea_IdtEmp', models.TextField(db_index=True, verbose_name=b'IdtEmp', blank=True)),
                ('iea_MatFun', models.TextField(db_index=True, verbose_name=b'MatFun', blank=True)),
                ('iea_NomPes', models.TextField(db_index=True, verbose_name=b'NomPes', blank=True)),
                ('iea_NomSol', models.TextField(db_index=True, verbose_name=b'NomSol', blank=True)),
                ('iea_NumCcr', models.TextField(db_index=True, verbose_name=b'NumCcr', blank=True)),
                ('iea_ObsRes', models.TextField(db_index=True, verbose_name=b'ObsRes', blank=True)),
                ('iea_PrcApt', models.TextField(db_index=True, verbose_name=b'PrcApt', blank=True)),
                ('iea_QtdApp', models.TextField(db_index=True, verbose_name=b'QtdApp', blank=True)),
                ('iea_RsvDir', models.TextField(db_index=True, verbose_name=b'RsvDir', blank=True)),
                ('iea_TaxFor', models.TextField(db_index=True, verbose_name=b'TaxFor', blank=True)),
                ('iea_TipInf', models.TextField(db_index=True, verbose_name=b'TipInf', blank=True)),
                ('iea_TipNac', models.TextField(db_index=True, verbose_name=b'TipNac', blank=True)),
                ('iea_TipPcv', models.TextField(db_index=True, verbose_name=b'TipPcv', blank=True)),
                ('iea_TipPdt', models.TextField(db_index=True, verbose_name=b'TipPdt', blank=True)),
                ('iea_TipPho', models.TextField(db_index=True, verbose_name=b'TipPho', blank=True)),
                ('iea_VlrPpa', models.TextField(db_index=True, verbose_name=b'VlrPpa', blank=True)),
                ('iea_VlrTch', models.TextField(db_index=True, verbose_name=b'VlrTch', blank=True)),
            ],
            options={
                'verbose_name': 'Processamento',
                'verbose_name_plural': 'Processamentos',
            },
            bases=(models.Model,),
        ),
    ]
